### ISSUE TITLE
moodle-local_navbarplus

### ISSUE THREAD

**Issue by piratanelcuore** [moodleuulm/moodle-local_navbarplus#12]
Hi!
I find a problem during installation of New Navbar Release 2020021800
My Moodle version is: Moodle 3.8.1 (Build: 20200113)

In the local_navbarplus version.php file i find this:

defined('MOODLE_INTERNAL') || die();

$plugin->component = 'local_navbarplus';
$plugin->version = 2020021800;
$plugin->release = 'v3.8-r1';
$plugin->requires = 2019111801.04;
$plugin->maturity = MATURITY_STABLE;

and doesn't work!

Just modified 
$plugin->requires = 2019111801.04; in $plugin->requires = 2019111801;
and now it works

**Comment by abias** [comment]
Hi @piratanelcuore ,

the requirement for Moodle core 2019111801.04 is correct and the installation of the updated plugin worked fine in our setup.

The reason that it does not work for you is that the plugin is requiring Moodle core 3.8.1+ and you only have 3.8.1. 

The reason for this requirement is that we had to include a fix for https://tracker.moodle.org/browse/MDL-67577 which was integrated upstream in Moodle core 3.8.1+ and will be formally released in 3.8.2.

If you can't update to Moodle core 3.8.1+ together with the update of this plugin, I would
* _not_ recommend to lower the required Moodle core version in the plugin as this will create an unsupported core-plugin combination.
* recommend that you stick to v3.7-r of the plugin until you can update to Moodle core 3.8.2. This combination will still be safe and working.

Sorry if this might have caused confusion.

Cheers,
Alex

**Comment by piratanelcuore** [comment]
Thank you! I've followed your instructions, and now it's work :-)
