### ISSUE TITLE
Exception - Call to undefined method tool_usertours\manager::get_current_tour() with Moodle 3.10

### ISSUE THREAD

**Issue by leonstr** [moodleuulm/moodle-local_navbarplus#13]
In Moodle 3.10 **tool_usertours\manager::get_current_tour()** was renamed **tool_usertours\manager::get_current_tours()** ([MDL-69739](https://tracker.moodle.org/browse/MDL-69739)).

See also forum post [Exception - Call to undefined method](https://moodle.org/mod/forum/discuss.php?d=415804).

**Comment by abias** [comment]
As commented in #16, this is solved by https://github.com/moodleuulm/moodle-local_navbarplus/commit/affda2e799d5b210d661da4d10d1e973dd919905.
