### ISSUE TITLE
How to custom top nav bar

### ISSUE THREAD

**Issue by wowbdg** [moodleuulm/moodle-local_navbarplus#18]
dear support

could you please help me, i wanti to make top nav bar like this :
![image](https://user-images.githubusercontent.com/86218176/122710051-b2613680-d289-11eb-87b7-8a8cdaaa7e41.png)

but, after i setup, icon look like this :
![image](https://user-images.githubusercontent.com/86218176/122707975-4b418300-d285-11eb-87ea-e4742226790f.png)
fav icon size is different, and i cant overide the size, even i put some css in my theme (as describe in readme file)
ps : i'm using moodle 3.10 with edwiser remui for my theme

thank you for yiour assistance.
wow

**Comment by abias** [comment]
Hi @wowbdg ,

I am really sorry, but Edwiser remui is a heavily modified theme and it's not unlikely that it does something to the navigation bar which distorts the icons in the way as you are seeing it now. We can't help you in this case. I would like to ask you to ask the Edwiser support if they can you help.

Thanks,
Alex
