### ISSUE TITLE
Assistance needed to display the username in the secure navbar during a quiz with SEB

### ISSUE THREAD

**Issue by Marihp** [moodleuulm/moodle-local_navbarplus#21]
Hi navbarplus team,

First of all, I want to express my appreciation for your hard work on this plugin. It has been incredibly helpful in our use case, and I am grateful for all the features it provides.

I am currently facing a challenge while using the plugin in combination with Safe Exam Browser (SEB). Specifically, I would like to display the username of the logged-in user in the secure navbar when presenting a quiz. At the moment, I haven’t found a way to make this work.

Could you kindly guide me on how to achieve this functionality? Is there a built-in feature that supports this, or would it require a custom modification? Any advice or pointers would be greatly appreciated.

Thanks again for your time and contribution to this excellent tool. Looking forward to your guidance!

Best regards,

**Comment by abias** [comment]
Hi @Marihp ,

thank you for raising this issue.

While this feature request is out of scope for this plugin, you might want to raise this issue in the Moodle Tracker to be solved in Moodle core. Recently, a similar issue was integrated on https://tracker.moodle.org/browse/MDL-75610 and I see a good chance that your proposal might be picked up for development as well.

Cheers,
Alex
