### ISSUE TITLE
Open in new tab not working

### ISSUE THREAD

**Issue by emmarichardson** [moodleuulm/moodle-local_navbarplus#4]
fa-envelope|https://mail2.ecboces.org/OWA|Webmail||false
Regardless of adding true or false at the end, the site opens in the same window...

**Comment by Kathrin84** [comment]
Hi Emma,
thanks for creating this issue on GitHub. I saw your post on the Moodle forum's thread, too. So I don't need to guide you to this place. :) That's fine.
I'll have a look at this issue.
Best, Kathrin

**Comment by Kathrin84** [comment]
Dear Emma,
there was a bug in my code I did not see. I fixed it in v3.4-r2 which you can download in Moodle's plugin repository.(https://moodle.org/plugins/download.php/16200/local_navbarplus_moodle34_2018030500.zip)
Thanks again and best, Kathrin
