### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by emmarichardson** [moodleuulm/moodle-local_navbarplus#5]
Ability to add icons on left side of navbar by or instead of custom links for example...

**Comment by Kathrin84** [comment]
Dear Emma,
thanks for this proposal. We will think about this. 
Unfortunately, right now, we cannot deal with this request for workload reasons. I will try to come back to this in the middle of this year. I hope this is okay for you.
Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @emmarichardson,
finally I had a chance to have a look at your feature request. Unfortunately it's not possible to get this done within this plugin. For the placement on the left side, the items need to be placed outside the structure the hook uses. And floating and such things don't have any effect here.
Within a theme, it should be possible to place these icons on the left side - so maybe you want to think about requesting this placement for your theme?
Sorry, for not being able to realize your request.
Best, Kathrin
