### ISSUE TITLE
why is moodle 3.5+ required?

### ISSUE THREAD

**Issue by actXc** [moodleuulm/moodle-local_navbarplus#7]
I would like to use it with 3.4
I tried to hack the version file - but then I get the following error message:

as Plugin "local_navbarplus" ist defekt oder veraltet. Der Prozess wird abgebrochen.

Weitere Informationen über diesen Fehler
Debug info: Plugin is not compatible with Moodle 2.x or later.
Error code: detectedbrokenplugin
Stack trace:

    line 554 of /lib/upgradelib.php: plugin_defective_exception thrown
    line 1850 of /lib/upgradelib.php: call to upgrade_plugins()
    line 694 of /admin/index.php: call to upgrade_noncore()

I can fully understand if you say "only 3.5 and above" but it was already working on lower versions, I can not find a branch of the old version.

**Comment by Kathrin84** [comment]
Hi Guido,
I assume you use this repository as your source for the plugin?

Just have a look at the Moodle's plugins repository:
https://moodle.org/plugins/pluginversions.php?plugin=local_navbarplus
There you can get the version suitable for older Moodle versions.
We recommend to always use the published code and not cloning this repo.

But if you want to use the gitHub code, others use our release tags to get the correct version for their Moodle instances.
Hacking the version PHP is no good idea, especially if you already installed a newer version.

I hope this info helps. Please let me know.

Best, Kathrin

**Comment by abias** [comment]
Hi Guido,

if you really want to hack the version.php to install the latest version of this plugin on a legacy Moodle, have a look at https://github.com/moodleuulm/moodle-local_navbarplus/blob/master/README.md#moodle-release-support where the necessary changes are described.

Apart from that, you can always fetch a matching version from https://github.com/moodleuulm/moodle-local_sandbox/releases or https://moodle.org/plugins/pluginversions.php?plugin=local_navbarplus as described by Kathrin.

Cheers,
Alex
