### ISSUE TITLE
CSS ID

### ISSUE THREAD

**Issue by scotthardwick** [moodleuulm/moodle-local_navbarplus#9]
Hi,
Quick note of a very minor item....

The built-in resetusertour comes across as
id="local_navbarplus_resetusertour" 

While user created items come across as
id="localnavbarplus-usercreateditemname"

I am not sure if they were supposed to be similar in the "local_navbarplus_" part, but seemed different enough to post a note.

Scott

**Comment by Kathrin84** [comment]
Hi @scotthardwick ,

thank you very much for raising this issue and for your excellent perception. Spontaneously, I would say that this is not intended and should be harmonized. Nevertheless, I'll have a closer look at the code regarding this issue after the holidays in the new year.

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @scotthardwick,

now I found time and had a look at the issue. Yes, the different naming was by mistake and I changed this in this commit: https://github.com/moodleuulm/moodle-local_navbarplus/commit/851d207735e7ddae8690b7c9e9900411002d153b

So, I close this issue as fixed.

Best, Kathrin

**Comment by scotthardwick** [comment]
Thank you so much Kathrin!  The plugins that you, Alexander, and ULM have released for the community are so very appreciated.  NavBarPlus and BoostNavigation are critically useful!  These functionalities should be built in to Moodle! ;-)

**Comment by Kathrin84** [comment]
Hi @scotthardwick,
thank you very much for kind words! :) :)
Best, Kathrin
